# Generated by Django 5.1 on 2024-08-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('games_played', models.IntegerField()),
                ('batting_average', models.DecimalField(decimal_places=3, max_digits=4)),
                ('home_runs', models.IntegerField()),
                ('singles', models.IntegerField()),
                ('doubles', models.IntegerField()),
                ('triples', models.IntegerField()),
                ('strikeouts', models.IntegerField()),
                ('walks', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
